### ISSUE TITLE
Task list?

### ISSUE THREAD

**Issue by Zefk** [solarus-games/solarus-sample-quest#9]
Maybe a task list will help?

**Outside World Tileset:**
- [ ] Water well
- [x] Mailbox
- [x] Graveyard brick tiles
- [x] Gravestones
- [x] Fence
- [x] Statues
- [ ] Wooden bridge
- [x] Log bridge
- [x] Stone bridge
- [ ] Boss building entrances
- [x] Whirlpool
- [ ] Waterfall
- [ ] Water cliffs
- [x] Log tunnels
- [ ] Fountain
- [ ] Clouds
- [x] Village floor bricks
- [ ] Village gate
- [x] Village grass walls
- [x] Store sign (Blacksmith, item shop, inn, etc)

**Comment by Zefk** [comment]
**Edit:** Finished them.
- Whirlpool
- Village floor bricks
- Village grass walls
- Store signs (Blacksmith, item shop, inn, etc)
- Log tunnels 
- Graveyard brick tiles
- Gravestones
- Fence
- Log bridge
- Stone bridge
- Mailbox
